version: '3'
services:
  app:
    container_name: samir-controlhe-usuario
    build: .
    depends_on:
      - database
    ports:
      - ${DOCKER_PORT}:${API_PORT}
    environment:
      DB_HOST: database
      DB_PORT: 5432
  database:
    container_name: samir-controlhe-usuario_db
    image: postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
    - ${DB_PORT}:5432
