import { User } from "../entities/User";

export interface ICreateCalculoLoteRequestDTO {
    numeroDoProcesso: string;
    nome: string;
    dataDeAjuizamento: string;
    cpf: string;
    termoInicial: string;
    termoFinal: string
    rmi: number;
    beneficio: string;
    numeroDoBeneficio: string;
    dataDePagamento: string;
    citacao: string;
    aps: string;
    recebeuBeneficio: boolean;
    nomeBeneficioBeneficioAcumulado?: string[];
    dataDeInicioBeneficioAcumulado?: string[];
    dataFinalBeneficioAcumulado?: string[];
    rmilBeneficioAcumulado?: string[];
    inicioJuros: string;
    dib?: string;
    salario13Obrigatorio: boolean;
    data: string[];
    reajusteAcumulado: number[];
    devido: number[];
    reajusteRecebido: number[];
    recebido: number[];
    salario: number[];
    correcao: number[];
    salarioCorrigido: number[];
    juros: number[];
    salarioJuros: number[];
    salarioTotal: number[]
    pacelasVencidas: number
    total_processos: number
    valor_total: number
    valor_juros: number
    valor_corrigido: number
    valorHonorarios: number
    iPvalorAnoAnterior: number
    iPvalorAnoAtual: number
    competenciaAnoAnterior: number
    competenciaAnoAtual: number
    porcentagemRMI: number;
    honorarioAdvocativosData?: string
    honorariosAdvocativos?: number;
    textoHonorarios?: string;
    decricaoJuros?: string;
    descricaoCorrecao?: string
    alcadaValor: number
    salariominimosAlcada: number
    alcadaJuros: number
    alcadaCorrecao: number
    alcadaTotal: number;
    textoPeriodoAlcada?: string
    alcadaJurosPorcentagem?: number
    alcadaCorrecaoPorcetagem?: number
    acordo?: number;
    tipoJuros: number;
    tipoCorrecao: number;
    possuiDecimoTerceiro?: boolean;
    possuiJuros?: boolean;
    alcada?: boolean;
    salarioMinimo?: boolean;
    limiteMinimoMaximo?: boolean;
    usuario?: number;
    atualizacao: string;
    dibAnterior?: string;
    url?: string;
    tipo?: string;
    porcentagemRmiBeneficioAcumulado?: number[];
    salario13ObrigatorioBeneficioAcumulado?: boolean[];
    salario13BeneficioAcumulado?: boolean[];
    salarioMinimoBeneficioAcumulado?: boolean[];
    limiteMinimoMaximoBeneficioAcumulado?: boolean[];
    selic?: boolean;
    conteudoHTML: string;
    idUser: User;

}